config/routes.rb
Mockup::Application.routes.draw do

  resources :welcomes

  resources :msg_show_log_histories

  resources :test_runs

  resources :known_issue_patterns

  resources :known_issues

	post 'msg_logs/search' => 'msg_logs#ajax_search'
	
  resources :msg_logs

	get 'msg_show_logs/ajax_get_increment' => 'msg_show_logs#ajax_get_increment'
	get 'msg_show_logs/ajax_get_known_issues' => 'msg_show_logs#ajax_get_known_issues'
	post 'msg_show_logs/ajax_add_known_issues' => 'msg_show_logs#ajax_add_known_issues'
	post 'msg_show_logs/ajax_remove_known_issues' => 'msg_show_logs#ajax_remove_known_issues'
	get 'msg_show_logs/indextbl' => 'msg_show_logs#indextbl'
	
  resources :msg_show_logs

  resources :msg_types

  resources :logs

  root 'welcome#index'

end

app/models/msg_log.rb
class MsgLog < ActiveRecord::Base
	belongs_to :msg_type
end

app/controllers/msg_logs_controller.rb
require 'time'
require 'json'

class MsgLogsController < ApplicationController
  before_action :set_msg_log, only: [:show, :edit, :update, :destroy]

  def	ajax_search
		collected_at = Time.parse(params[:collected_at])
		message = params[:message]
		page = params[:page].to_i
		page_limit = params[:page_limit].to_i
		filter = params[:filter]
		orderby = params[:orderby]
		if !orderby || orderby.empty?
			orderby = "recorded_at"
		end
		puts "haha #{filter.inspect}"
		detailed_messages = []

		pattern = message.gsub("#", "%").gsub(/\s+/, ' ')

		condition = "message LIKE ? AND recorded_at < ?"
		values = [pattern, collected_at]

		if filter
			if filter["substring"] && !filter["substring"].empty?
				condition << " AND message LIKE ?"
				values << "%#{filter["substring"]}%"
			end
			if filter["msid_from"] && !filter["msid_from"].empty?
				condition << " AND msid::bigint >= ?"
				values << filter["msid_from"]
			end
			if filter["msid_to"] && !filter["msid_to"].empty?
				condition << " AND msid::bigint <= ?"
				values << filter["msid_to"]
			end
			if filter["imsi_from"] && !filter["imsi_from"].empty?
				condition << " AND imsi::bigint >= ?"
				values << filter["imsi_from"]
			end
			if filter["imsi_to"] && !filter["imsi_to"].empty?
				condition << " AND imsi::bigint <= ?"
				values << filter["imsi_to"]
			end
		end
		
		total_count = MsgLog.where(condition, *values).count
		
		msg_logs = MsgLog.where(condition, *values).limit(page_limit).offset((page - 1) * page_limit).order(orderby)

		msg_logs.each do |l|			
			detailed_message = {}
			detailed_message[:msg_type] = l.msg_type.name
			detailed_message[:recorded_at] = l.recorded_at
			detailed_message[:msid] = l.msid
			detailed_message[:imsi] = l.imsi
			detailed_message[:last_event] = l.last_event
			detailed_message[:last_tcs] = l.last_tcs
			detailed_message[:message] = l.message
			detailed_messages << detailed_message
		end

		data = {
			:page_count => (total_count / page_limit.to_f).ceil,
			:detailed_messages => detailed_messages
		}
		
		respond_to do |f|
			f.json { render :json => data }
		end
	end
	
  # GET /msg_logs
  # GET /msg_logs.json
  def index
    @msg_logs = MsgLog.all
  end

  # GET /msg_logs/1
  # GET /msg_logs/1.json
  def show
  end

  # GET /msg_logs/new
  def new
    @msg_log = MsgLog.new
  end

  # GET /msg_logs/1/edit
  def edit
  end

  # POST /msg_logs
  # POST /msg_logs.json
  def create
    @msg_log = MsgLog.new(msg_log_params)

    respond_to do |format|
      if @msg_log.save
        format.html { redirect_to @msg_log, notice: 'Msg log was successfully created.' }
        format.json { render action: 'show', status: :created, location: @msg_log }
      else
        format.html { render action: 'new' }
        format.json { render json: @msg_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /msg_logs/1
  # PATCH/PUT /msg_logs/1.json
  def update
    respond_to do |format|
      if @msg_log.update(msg_log_params)
        format.html { redirect_to @msg_log, notice: 'Msg log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @msg_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /msg_logs/1
  # DELETE /msg_logs/1.json
  def destroy
    @msg_log.destroy
    respond_to do |format|
      format.html { redirect_to msg_logs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_msg_log
      @msg_log = MsgLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def msg_log_params
      params.require(:msg_log).permit(:recorded_at, :message)
    end
end

app/helpers/msg_logs_helper.rb
module MsgLogsHelper
end

app/views/msg_logs/_form.html.erb
<%= form_for(@msg_log) do |f| %>
  <% if @msg_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@msg_log.errors.count, "error") %> prohibited this msg_log from being saved:</h2>

      <ul>
      <% @msg_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recorded_at %><br>
    <%= f.datetime_select :recorded_at %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/msg_logs/edit.html.erb
<h1>Editing msg_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @msg_log %> |
<%= link_to 'Back', msg_logs_path %>

app/views/msg_logs/index.html.erb
<h1>Listing msg_logs</h1>

<table>
  <thead>
    <tr>
      <th>Recorded at</th>
      <th>Message</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @msg_logs.each do |msg_log| %>
      <tr>
        <td><%= msg_log.recorded_at %></td>
        <td><%= msg_log.message %></td>
        <td><%= link_to 'Show', msg_log %></td>
        <td><%= link_to 'Edit', edit_msg_log_path(msg_log) %></td>
        <td><%= link_to 'Destroy', msg_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Msg log', new_msg_log_path %>

app/views/msg_logs/new.html.erb
<h1>New msg_log</h1>

<%= render 'form' %>

<%= link_to 'Back', msg_logs_path %>

app/views/msg_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recorded at:</strong>
  <%= @msg_log.recorded_at %>
</p>

<p>
  <strong>Message:</strong>
  <%= @msg_log.message %>
</p>

<%= link_to 'Edit', edit_msg_log_path(@msg_log) %> |
<%= link_to 'Back', msg_logs_path %>