config/routes.rb
Mockup::Application.routes.draw do

  resources :welcomes

  resources :msg_show_log_histories

  resources :test_runs

  resources :known_issue_patterns

  resources :known_issues

	post 'msg_logs/search' => 'msg_logs#ajax_search'
	
  resources :msg_logs

	get 'msg_show_logs/ajax_get_increment' => 'msg_show_logs#ajax_get_increment'
	get 'msg_show_logs/ajax_get_known_issues' => 'msg_show_logs#ajax_get_known_issues'
	post 'msg_show_logs/ajax_add_known_issues' => 'msg_show_logs#ajax_add_known_issues'
	post 'msg_show_logs/ajax_remove_known_issues' => 'msg_show_logs#ajax_remove_known_issues'
	get 'msg_show_logs/indextbl' => 'msg_show_logs#indextbl'
	
  resources :msg_show_logs

  resources :msg_types

  resources :logs

  root 'welcome#index'

end

app/controllers/msg_types_controller.rb
class MsgTypesController < ApplicationController
  before_action :set_msg_type, only: [:show, :edit, :update, :destroy]

  # GET /msg_types
  # GET /msg_types.json
  def index
    @msg_types = MsgType.all
  end

  # GET /msg_types/1
  # GET /msg_types/1.json
  def show
  end

  # GET /msg_types/new
  def new
    @msg_type = MsgType.new
  end

  # GET /msg_types/1/edit
  def edit
  end

  # POST /msg_types
  # POST /msg_types.json
  def create
    @msg_type = MsgType.new(msg_type_params)

    respond_to do |format|
      if @msg_type.save
        format.html { redirect_to @msg_type, notice: 'Msg type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @msg_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @msg_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /msg_types/1
  # PATCH/PUT /msg_types/1.json
  def update
    respond_to do |format|
      if @msg_type.update(msg_type_params)
        format.html { redirect_to @msg_type, notice: 'Msg type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @msg_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /msg_types/1
  # DELETE /msg_types/1.json
  def destroy
    @msg_type.destroy
    respond_to do |format|
      format.html { redirect_to msg_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_msg_type
      @msg_type = MsgType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def msg_type_params
      params.require(:msg_type).permit(:name)
    end
end

app/helpers/msg_types_helper.rb
module MsgTypesHelper
end

app/views/msg_types/_form.html.erb
<%= form_for(@msg_type) do |f| %>
  <% if @msg_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@msg_type.errors.count, "error") %> prohibited this msg_type from being saved:</h2>

      <ul>
      <% @msg_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/msg_types/edit.html.erb
<h1>Editing msg_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @msg_type %> |
<%= link_to 'Back', msg_types_path %>

app/views/msg_types/index.html.erb
<h1>Listing msg_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @msg_types.each do |msg_type| %>
      <tr>
        <td><%= msg_type.name %></td>
        <td><%= link_to 'Show', msg_type %></td>
        <td><%= link_to 'Edit', edit_msg_type_path(msg_type) %></td>
        <td><%= link_to 'Destroy', msg_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Msg type', new_msg_type_path %>

app/views/msg_types/new.html.erb
<h1>New msg_type</h1>

<%= render 'form' %>

<%= link_to 'Back', msg_types_path %>

app/views/msg_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @msg_type.name %>
</p>

<%= link_to 'Edit', edit_msg_type_path(@msg_type) %> |
<%= link_to 'Back', msg_types_path %>