config/routes.rb
Mockup::Application.routes.draw do

  resources :welcomes

  resources :msg_show_log_histories

  resources :test_runs

  resources :known_issue_patterns

  resources :known_issues

	post 'msg_logs/search' => 'msg_logs#ajax_search'
	
  resources :msg_logs

	get 'msg_show_logs/ajax_get_increment' => 'msg_show_logs#ajax_get_increment'
	get 'msg_show_logs/ajax_get_known_issues' => 'msg_show_logs#ajax_get_known_issues'
	post 'msg_show_logs/ajax_add_known_issues' => 'msg_show_logs#ajax_add_known_issues'
	post 'msg_show_logs/ajax_remove_known_issues' => 'msg_show_logs#ajax_remove_known_issues'
	get 'msg_show_logs/indextbl' => 'msg_show_logs#indextbl'
	
  resources :msg_show_logs

  resources :msg_types

  resources :logs

  root 'welcome#index'

end

app/models/known_issue.rb
class KnownIssue < ActiveRecord::Base
	has_and_belongs_to_many :known_issue_patterns, :join_table => "known_issue_patterns_known_issues"
	has_and_belongs_to_many :msg_show_logs
end

app/controllers/known_issues_controller.rb
class KnownIssuesController < ApplicationController
  before_action :set_known_issue, only: [:show, :edit, :update, :destroy]

  # GET /known_issues
  # GET /known_issues.json
  def index
    @known_issues = KnownIssue.all
		d = [ ]
		@known_issues.each do |i|
			d1 = { }
			d1[:id] = i.id
			d1[:name] = i.name
			d1[:patterns] = i.known_issue_patterns.map { |p| p.content }.join(",")
			d << d1
		end
		respond_to do |f|
			f.json { render :json => d }
		end
  end

  # GET /known_issues/1
  # GET /known_issues/1.json
  def show
  end

  # GET /known_issues/new
  def new
    @known_issue = KnownIssue.new
  end

  # GET /known_issues/1/edit
  def edit
  end

  # POST /known_issues
  # POST /known_issues.json
  def create

		name = params[:name]
		patterns = params[:patterns].split(',')
		msg_show_log_id = params[:msg_show_log_id]
		puts "#{patterns}"
		pattern_objs = []
		patterns.each do |p|
			tmp = KnownIssuePattern.where(:content => p).first
			if tmp
				pattern_objs << tmp
			else
				newp = KnownIssuePattern.new
				newp.content = p
				newp.save
				pattern_objs << newp
			end
		end

		@known_issue = KnownIssue.new
		@known_issue.name = name
		@known_issue.known_issue_patterns = pattern_objs
		@known_issue.msg_show_logs << MsgShowLog.find(msg_show_log_id)

    respond_to do |format|
      if @known_issue.save
				d = { :result => "ok" }
				puts "#{d.inspect}"
        format.json { render :json => d }
      else
        format.json { render json: @known_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /known_issues/1
  # PATCH/PUT /known_issues/1.json
  def update
    respond_to do |format|
      if @known_issue.update(known_issue_params)
        format.html { redirect_to @known_issue, notice: 'Known issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @known_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /known_issues/1
  # DELETE /known_issues/1.json
  def destroy
    @known_issue.destroy
    respond_to do |format|
      format.html { redirect_to known_issues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_known_issue
      @known_issue = KnownIssue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def known_issue_params
      params.require(:known_issue).permit(:name)
    end
end

app/helpers/known_issues_helper.rb
module KnownIssuesHelper
end

app/views/known_issues/_form.html.erb
<%= form_for(@known_issue) do |f| %>
  <% if @known_issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@known_issue.errors.count, "error") %> prohibited this known_issue from being saved:</h2>

      <ul>
      <% @known_issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/known_issues/edit.html.erb
<h1>Editing known_issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @known_issue %> |
<%= link_to 'Back', known_issues_path %>

app/views/known_issues/index.html.erb
<h1>Listing known_issues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @known_issues.each do |known_issue| %>
      <tr>
        <td><%= known_issue.name %></td>
        <td><%= link_to 'Show', known_issue %></td>
        <td><%= link_to 'Edit', edit_known_issue_path(known_issue) %></td>
        <td><%= link_to 'Destroy', known_issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Known issue', new_known_issue_path %>

app/views/known_issues/new.html.erb
<h1>New known_issue</h1>

<%= render 'form' %>

<%= link_to 'Back', known_issues_path %>

app/views/known_issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @known_issue.name %>
</p>

<%= link_to 'Edit', edit_known_issue_path(@known_issue) %> |
<%= link_to 'Back', known_issues_path %>