config/routes.rb
Mockup::Application.routes.draw do

  resources :welcomes

  resources :msg_show_log_histories

  resources :test_runs

  resources :known_issue_patterns

  resources :known_issues

	post 'msg_logs/search' => 'msg_logs#ajax_search'
	
  resources :msg_logs

	get 'msg_show_logs/ajax_get_increment' => 'msg_show_logs#ajax_get_increment'
	get 'msg_show_logs/ajax_get_known_issues' => 'msg_show_logs#ajax_get_known_issues'
	post 'msg_show_logs/ajax_add_known_issues' => 'msg_show_logs#ajax_add_known_issues'
	post 'msg_show_logs/ajax_remove_known_issues' => 'msg_show_logs#ajax_remove_known_issues'
	get 'msg_show_logs/indextbl' => 'msg_show_logs#indextbl'
	
  resources :msg_show_logs

  resources :msg_types

  resources :logs

  root 'welcome#index'

end

app/models/msg_show_log.rb
class MsgShowLog < ActiveRecord::Base
	belongs_to :msg_type
	belongs_to :test_run
	has_many   :msg_show_log_histories
	has_and_belongs_to_many :known_issues
end

app/controllers/msg_show_logs_controller.rb
require 'json'

class MsgShowLogsController < ApplicationController
  before_action :set_msg_show_log, only: [:show, :edit, :update, :destroy]

	def ajax_get_known_issues
		msg_show_log_id = params[:msg_show_log_id]
		msg_show_log = MsgShowLog.find(msg_show_log_id)
		d = [ ]
		msg_show_log.known_issues.each do |i|
			d1 = { }
			d1[:id] = i.id
			d1[:name] = i.name
			d1[:patterns] = i.known_issue_patterns.map { |p| p.content }.join(",")
			d << d1
		end
		render json: d
	end

	def ajax_add_known_issues
		msg_show_log_id = params[:msg_show_log_id].to_i
		known_issue_id = params[:known_issue_id].to_i
		msg_show_log = MsgShowLog.find(msg_show_log_id)
		msg_show_log.known_issues << KnownIssue.find(known_issue_id)
		d = { }
		if msg_show_log.save
			d[:result] = "ok"
		else
			d[:result] = "nok"
		end
		render json: d
	end

	def ajax_remove_known_issues
		msg_show_log_id = params[:msg_show_log_id].to_i
		known_issue_id = params[:known_issue_id].to_i
		msg_show_log = MsgShowLog.find(msg_show_log_id)
		msg_show_log.known_issues.delete(KnownIssue.find(known_issue_id))
		d = { }
		if msg_show_log.save
			d[:result] = "ok"
		else
			d[:result] = "nok"
		end
		render json: d
	end

	def ajax_get_increment
		d = {
			increment: rand(50),
			collected_at: Time.now
		}
		respond_to do |f|
			f.json { render :json => d }
		end
	end
	
  # GET /msg_show_logs
  # GET /msg_show_logs.json
  def index
    @msg_show_logs = MsgShowLog.order(count: :desc).paginate(:page => params[:page], :per_page => 20)
  end

	def indextbl
		update_all(params[:test_run_id])
    @msg_show_logs = MsgShowLog.order(count: :desc).paginate(:page => params[:page], :per_page => 20)
		render "msg_show_logs/indextbl", :layout => false
  end
	
  # GET /msg_show_logs/1
  # GET /msg_show_logs/1.json
  def show
		#@single_msg_records = MsgShowLog.where(message: MsgShowLog.find(params[:id]).message).order(collected_at: :desc)
  end

  # GET /msg_show_logs/new
  def new
    @msg_show_log = MsgShowLog.new
  end

  # GET /msg_show_logs/1/edit
  def edit
  end

  # POST /msg_show_logs
  # POST /msg_show_logs.json
  def create
    @msg_show_log = MsgShowLog.new(msg_show_log_params)

    respond_to do |format|
      if @msg_show_log.save
        format.html { redirect_to @msg_show_log, notice: 'Msg show log was successfully created.' }
        format.json { render action: 'show', status: :created, location: @msg_show_log }
      else
        format.html { render action: 'new' }
        format.json { render json: @msg_show_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /msg_show_logs/1
  # PATCH/PUT /msg_show_logs/1.json
  def update
    respond_to do |format|
      if @msg_show_log.update(msg_show_log_params)
        format.html { redirect_to @msg_show_log, notice: 'Msg show log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @msg_show_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /msg_show_logs/1
  # DELETE /msg_show_logs/1.json
  def destroy
    @msg_show_log.destroy
    respond_to do |format|
      format.html { redirect_to msg_show_logs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_msg_show_log
      @msg_show_log = MsgShowLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def msg_show_log_params
      params.require(:msg_show_log).permit(:count, :message, :collected_at)
    end

		def update_single(id)
			m = MsgShowLog.find(id)
			if m
				collected_at = Time.now
				# probability of remaining unchanged is 0.2
				unless rand(5) == 0
					m.count += rand(50)
				end
				m.save
				h = MsgShowLogHistory.new
				h.count = m.count
				h.collected_at = m.collected_at
				h.msg_show_log = m
				h.save
			end
		end

		def update_all(test_run_id)
			collected_at = Time.now
			MsgShowLog.all.each do |m|
				# probability of remaining unchanged is 0.2
				unless rand(5) == 0
					m.count += rand(50)
				end
				m.collected_at = collected_at
				m.save
				h = MsgShowLogHistory.new
				h.count = m.count
				h.collected_at = collected_at
				h.msg_show_log = m
				h.save
			end
			# probability of having new entries is 0.1
			puts "update all ... "
			t = MsgType.find(1)
			if rand(10) == 0
				m = MsgShowLog.new
				m.msg_type = t
				m.count = 1
				m.collected_at = collected_at
				m.message = "Randomly added error message group #{MsgShowLog.count + 1}"
				m.test_run = TestRun.find(test_run_id)
				m.save
				h = MsgShowLogHistory.new
				h.count = m.count
				h.collected_at = m.collected_at
				h.msg_show_log = m
				h.save
			end
			
		end
		
end

app/helpers/msg_show_logs_helper.rb
module MsgShowLogsHelper
end

app/views/msg_show_logs/_form.html.erb
<%= form_for(@msg_show_log) do |f| %>
  <% if @msg_show_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@msg_show_log.errors.count, "error") %> prohibited this msg_show_log from being saved:</h2>

      <ul>
      <% @msg_show_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :collected_at %><br>
    <%= f.datetime_select :collected_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/msg_show_logs/_tbl_msg_show_logs.html.erb
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th style="width:60px;">Type</th>
      <th style="width:60px;">Count</th>
      <th>Message</th>
      <th colspan="2">Known Issues</th>
    </tr>
  </thead>
  <tbody>
		<% i = 0 %>
		<% @msg_show_logs.each do |m| %>
			<% i += 1 %>
			<% color = m.count >= 4000 ? "danger" : (m.count >= 3000 ? "warning" : "") %>
      <tr>
        <td><%= m.msg_type.name %></td>
				<td><%= m.count %></td>
				<td id="full-message" class="clickable redirect hover <%= color %>" href="<%= msg_show_log_path(m) %>"><%= m.message.gsub(/\s*,\s*/, ',').gsub(/,/, ', ') %></td>
        <td style="width:30px;">
					<% icon_class = m.known_issues.empty? ? "glyphicon-star-empty" : "glyphicon-star" %>
					<span class="glyphicon <%= icon_class %> clickable" data-toggle="collapse" data-target="row<%= i %>" id="row<%= i %>"></span>
				</td>
        <td>
          <button class="btn btn-default btn-xs btn-known-issue-details" data-msg-show-log-id="<%= m.id %>"><span class="glyphicon glyphicon-list-alt"></span>
						&nbsp;Details</button>
				</td>
      </tr>
      <tr class="collapse success" id="row<%= i %>">
        <td></td>
        <td></td>
				<td colspan="3">
					<% m.known_issues.each do |i| %>
						<span class="label label-warning"><%= i.name %></span>
					<% end %>
				</td>
      </tr>
		<% end %>
  </tbody>
</table>

<div class="row">
	<%= will_paginate @msg_show_logs,
			:renderer => BootstrapPagination::Rails,
			:class => "pagination-sm pagination-condensed pull-right",
			:previous_label => "<<",
			:next_label => ">>" %>
</div>

<div class="modal fade" id="known-issue-modal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close h4-align" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Known Issue Details</h4>
      </div>
      <div class="modal-body">
        <input type="hidden" name="msg-show-log-id" value=""/>
        <pre id="known-issue-context">
        </pre>
				<button type="button" class="btn btn-default" id="add-known-issue"><span class="glyphicon glyphicon-list"></span> &nbsp;Add</button>
				<button type="button" class="btn btn-default" id="create-known-issue"><span class="glyphicon glyphicon-plus"></span> &nbsp;New</button>
        <hr class="hr-condensed"/>
        <div class="alert alert-success" id="known-issue-added-alert" hidden></div>
				<div class="alert alert-success" id="known-issue-saved-alert" hidden></div>
				<div class="alert alert-success" id="known-issue-removed-alert" hidden></div>

        <div class="panel panel-primary hidden" id="add-known-issue">
          <div class="panel-heading">
						<button type="button" class="close panel-close h4-align">&times;</button>
            <h4 class="panel-title">Add Existing Known Issue</h4>
					</div>
          <div class="panel-body">
            <div class="form-group">
							<select class="form-control" name="existing-known-issues">
              </select>
						</div>
						<button type="button" class="btn btn-success btn-block" id="add-known-issue-go"><span class="glyphicon glyphicon-floppy-save"></span> &nbsp;Save</button>
					</div>
				</div>

        <div class="hidden panel panel-primary" id="new-known-issue">
          <div class="panel-heading">
						<button type="button" class="close panel-close h4-align">&times;</button>
            <h4 class="panel-title">Create Known Issue</h4>
					</div>
          <div class="panel-body">
            <div class="form-group">
              <label for="known-issue-name">Name</label>
              <input class="form-control" type="text" name="known-issue-name" value=""/>
						</div>
						<div class="form-group" id="known-issue-patterns">
              <label for="known-issue-patterns">Patterns</label>
              <select multiple class="form-control" name="known-issue-patterns" style="padding-top:12px; padding-bottom:12px;">
              </select>
						</div>
						<button type="button" class="btn btn-success btn-block" id="create-known-issue-go"><span class="glyphicon glyphicon-floppy-save"></span> &nbsp;Save</button>
					</div>
				</div>
				
				<table class="table table-condensed table-hover" id="tbl-known-issue-details">
					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th style="width:70%;">Patterns</th>
              <th style="width:50px;"></th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/msg_show_logs/edit.html.erb
<h1>Editing msg_show_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @msg_show_log %> |
<%= link_to 'Back', msg_show_logs_path %>

app/views/msg_show_logs/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Home', welcomes_path %></li>
  <li class="active">Statistics</li>
</ol>

<div class="row">
	<div class="col-md-6">
		<h3 class="h-btn-sm-align">Message Counters - <%= @msg_show_logs.first.test_run.name %></h3>
	</div>
  <div class="col-md-6 btn-parent">
		<div class="btn-group btn-group-sm pull-right">
			<button id="cancel_refresh" class="btn btn-default"><span class="glyphicon glyphicon-stop"></span></button>
			<button id="start_refresh" class="btn btn-default disabled"><span class="glyphicon glyphicon-play"></span></button>
			<button id="refresh" class="btn btn-default disabled"><span class="glyphicon glyphicon-refresh"></span></button>
		</div>
	</div>
</div>

<hr class="hr-condensed"/>

<div class="refreshable" data-test-run-id="<%= @msg_show_logs.first.test_run.id %>">
	<%= render "tbl_msg_show_logs" %>
</div>

app/views/msg_show_logs/indextbl.html.erb
<%= render "tbl_msg_show_logs" %>

app/views/msg_show_logs/new.html.erb
<h1>New msg_show_log</h1>

<%= render 'form' %>

<%= link_to 'Back', msg_show_logs_path %>

app/views/msg_show_logs/show.html.erb
<ol class="breadcrumb">
	<li><%= link_to 'Home', welcomes_path %></li>
  <li><%= link_to 'Statistics', msg_show_logs_path %></li>
  <li class="active">Details</li>
</ol>

<div class="row">
	<div class="col-md-6">
		<h3 class="h-btn-sm-align">Message Group</h3>
	</div>
</div>
<hr class="hr-condensed"/>
<pre id="msg-group"><%= @msg_show_log.message %></pre>

<br/>

<div class="row">
  <div class="col-md-3 col-md-rcompact">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="row">
					<div class="col-md-9">
						<h4 class="panel-title-btn-sm-align"><span class="glyphicon glyphicon-search"></span>
							&nbsp;Message Details</h4>
					</div>
					<div class="col-md-3 btn-parent">
						<div class="btn-group btn-group-sm pull-right">
							<button id="search-reset" class="btn btn-default btn-danger">Reset</button>
						</div>
					</div>
				</div>
			</div>
			<div class="panel-body panel-body-condensed">
				<div class="alert alert-info alert-condensed">
          <small>Hint: Click dots to select timestamps.</small>
					<button type="button" class="close alert-close">&times;</button>
				</div>

				<form role="form">
					<div class="form-group">
						<label for="start">Start Timestamp</label>
            <div class="input-group date datetimepicker input-group-sm" data-date-format="YYYY-MM-DDThh:mm:ssZ">
							<input type="text" class="form-control" id="start-ts">
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-calendar"></span>
							</span>
						</div>
					</div>
					<div class="form-group">
						<label for="start">End Timestamp</label>
            <div class="input-group date datetimepicker input-group-sm" data-date-format="YYYY-MM-DDThh:mm:ssZ">
							<input type="text" class="form-control" id="end-ts">
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-calendar"></span>
							</span>
						</div>
					</div>
					<button id="search-go" class="btn btn-primary btn-block">Go!</button>
				</form>
				
			</div>
		</div>
	</div>
  <div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="row">
					<div class="col-md-6">
						<h4 class="panel-title-btn-sm-align"><span class="glyphicon glyphicon-stats"></span>
							&nbsp;Trend</h4>
					</div>
					<div class="col-md-6 btn-parent">
						<div class="btn-group btn-group-sm pull-right">
							<button id="cancel_refresh" class="btn btn-default"><span class="glyphicon glyphicon-stop"></span></button>
							<button id="start_refresh" class="btn btn-default disabled"><span class="glyphicon glyphicon-play"></span></button>
							<button id="refresh" class="btn btn-default disabled"><span class="glyphicon glyphicon-refresh"></span></button>
						</div>
					</div>
				</div>
			</div>
			<div class="panel-body">
				<div class="center-block" id="chart" data-count="<%= @msg_show_log.msg_show_log_histories.map { |h| h.count }.join(",") %>" datax="<%= @msg_show_log.msg_show_log_histories.map { |h| h.collected_at.localtime.strftime("%FT%T%:z") }.sort.join(",") %>" data-refresh-url="<%= msg_show_logs_ajax_get_increment_path %>">
							
				</div>
			</div>
		</div>
	</div>
</div>

<br/>

<div class="modal fade" id="details-modal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close h4-align" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Message Details</h4>
      </div>
      <div class="modal-body">
				<div class="alert alert-info alert-condensed">
          <small>Hint: Click the rows the see full message.</small>
					<button type="button" class="close alert-close">&times;</button>
				</div>
        <div class="row">
          <div class="col-md-4">
						<div id="msg-logs-filter" class="input-group input-group-sm" style="margin-top: 4px;">
							<span class="input-group-addon glyphicon glyphicon-search" style="top: 0px;"></span>
							<input type="text" class="form-control" id="filter-content" placeholder="Filter results ...">
							<span class="input-group-btn">
								<button class="btn btn-default" id="filter-go" type="button">Go!</button>
								<button class="btn btn-default" id="filter-advanced" type="button"><span class="glyphicon glyphicon-wrench"></span></button>
							</span>
						</div>
					</div>
					<div class="pagination-container col-md-8">
						<ul class="pagination pagination-sm pagination-condensed pull-right">
							
						</ul>
					</div>
				</div>

        <br/>

        <div class="panel panel-primary hidden" id="filter-advanced">
          <div class="panel-heading">
						<button type="button" class="close panel-close h4-align">&times;</button>
						<h4 class="panel-title"><span class="glyphicon glyphicon-search"></span>&nbsp;Advanced Search</h4>
					</div>
          <div class="panel-body">
            <div class="form">
							<div class="form-group">
								<label for="" class="control-label">MSID Range</label>
								<div class="row">
                  <div class="col-md-6 col-md-rcompact-5">
                    <div class="input-group">
                      <span class="input-group-addon">From</span>
											<input class="form-control" type="text" name="msid-from" value=""/>
										</div>
									</div>
                  <div class="col-md-6 col-md-lcompact-5">
										<div class="input-group">
                      <span class="input-group-addon">To</span>
											<input class="form-control" type="text" name="msid-to" value=""/>
										</div>
									</div>
                </div>
							</div>
							<div class="form-group">
								<label for="" class="control-label">IMSI Range</label>
								<div class="row">
                  <div class="col-md-6 col-md-rcompact-5">
                    <div class="input-group">
                      <span class="input-group-addon">From</span>
											<input class="form-control" type="text" name="imsi-from" value=""/>
										</div>
									</div>
                  <div class="col-md-6 col-md-lcompact-5">
										<div class="input-group">
                      <span class="input-group-addon">To</span>
											<input class="form-control" type="text" name="imsi-to" value=""/>
										</div>
									</div>
                </div>
							</div>
							<button id="filter-advanced-go" class="btn btn-success btn-block">Go!</button>
						</div>
					</div>
				</div>

				<table class="table table-condensed table-bordered table-hover" id="tbl-msg-details">
					<thead>
						<tr>
							<th>#</th>
							<th>Type</th>
							<th class="clickable" data-order="recorded_at" data-order-desc="false" data-order-active="true">Timestamp <span class="glyphicon glyphicon-sort-by-attributes"></span></th>
              <th style="min-width:80px;" class="clickable" data-order="msid::bigint">MSID&nbsp;</th>
              <th style="min-width:80px;" class="clickable" data-order="imsi::bigint">IMSI&nbsp;</th>
							<th>Last Event</th>
							<th>Last TCs</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->